Fixing external links not redirecting properly
codeforpdx/codepdx_website pull request #110
Opened 2024-02-01 01:48 UTC by andycwilliams

## This PR:

Resolves #82 

Doesn't directly address that issue, since much of it was already finished. However, the social media links in the footer still needed to be fixed. So these kind of dovetail and that can finally be closed once this is done.

Currently they don't actually direct to the websites they're pointed to. I removed `component={ReactRouterLink}` from the social media `Link` component, which for me fixes the issue. 

## Future Steps/PRs Needed to Finish This Work (optional):

Test it and make sure it works on other devices and browsers.

Also, we discussed having a separate `development` branch for working with, rather than using the main branch itself. I can create one now and then change this PR so it merges with that, if we want.

2024-02-02 02:29 UTC, Jared-Krajewski requested changes
I'm not sure this PR fixes anything. The issue in question is regarding the legal links which I had quickly fixed before hosting the site. Footer links should be working prior to this PR with the exception of the socialLinks that all point back to the website. The only change in this PR removes `component={ReactRouterLink}` from the social links which technically does nothing since they are all external links. It can still be removed but my suggestion is to update that issue to include fixing the social links as well and add that to this PR.

2024-02-06 03:37 UTC, andycwilliams commented
When I test it, the social media links just point back to the website yet removing just `component={ReactRouterLink}` resolves the issue. So at least for my machine it does fix them.

2024-02-06 03:46 UTC, Jared-Krajewski commented
> When I test it, the social media links just point back to the website yet removing just `component={ReactRouterLink}` resolves the issue. So at least for my machine it does fix them.

Interesting. When I checked it again, that does fix it. Maybe I had a page load error when I tested it before.

2024-02-06 03:50 UTC, andycwilliams commented
> > When I test it, the social media links just point back to the website yet removing just `component={ReactRouterLink}` resolves the issue. So at least for my machine it does fix them.
> 
> Interesting. When I checked it again, that does fix it. Maybe I had a page load error when I tested it before.

Just tested some more. I believe it's due to how the `Link` component for social media uses `href={href}` whereas the one for legal links uses `to={link.href}` instead. When I change the legal links to also use `href={href}` (while keeping the react router link component), it breaks the links and redirects them to the website just like the social media links.

I can leave it as is, or change one so it matches the other. I don't know if using `href` is better than `to` or vice versa, or if it matters.

2024-02-06 23:40 UTC, andycwilliams commented
Not sure if I overengineered it, but the button should navigate to the top of the homepage now.

Also I removed the `reactRouterLink` import because by changing how the `Link`s are set up, it is no longer necessary. They now use `href` but I can change it to `to` instead if preferred. Then `reactRouterLink` would need to be added back.

2024-03-14 15:48 UTC, Jared-Krajewski requested changes
some extra code that can be removed, then should be good to go.

2024-03-14 15:48 UTC, Jared-Krajewski commented on src/components/global/Footer.jsx
> +import { useNavigate } from 'react-router-dom';
not necessary, theres no real internal routing going on here. the code pdx just scrolls to top and is the only internal link.

2024-03-14 15:48 UTC, Jared-Krajewski commented on src/components/global/Footer.jsx
> +const renderLegalLinks = (navigate) => {
`navigate` arg can be removed

2024-03-14 15:48 UTC, Jared-Krajewski commented on src/components/global/Footer.jsx
> +  const navigate = useNavigate();
can be removed.

2024-03-14 15:48 UTC, Jared-Krajewski commented on src/components/global/Footer.jsx
> +        {renderLegalLinks(navigate)}
should work fine with just `{renderLegalLinks()}`

2024-03-14 15:48 UTC, Jared-Krajewski commented on src/components/global/Footer.jsx
> +                  navigate('/');
`navigate('/');` can be removed, the scroll to top takes care of that links functionality since it stays on same page.

2024-03-14 19:48 UTC, andycwilliams commented
@Jared-Krajewski It looks like the Discord invite is invalid. It's telling me it might be expired or I may not have permission to join.

I'm testing it on different browsers, where I'm not already logged in, and it's the same.

2024-03-16 17:27 UTC, Jared-Krajewski commented
> @Jared-Krajewski It looks like the Discord invite is invalid. It's telling me it might be expired or I may not have permission to join.
> 
> I'm testing it on different browsers, where I'm not already logged in, and it's the same.

interesting, it was working for me. I can make yet another new one and push it. Does that mean the discord link in the volunteer section is also broken for you? not sure why invites that 'dont' expire, keep expiring.

2024-03-16 17:34 UTC, Jared-Krajewski approved these changes
Good to merge, thanks.

2024-03-16 19:35 UTC, merged