Adding Urban Systems to secondary partners
codeforpdx/codepdx_website pull request #111
Opened 2024-02-01 03:55 UTC by andycwilliams

## This PR:

Resolves #106 

Adds URBAN.SYSTEMS to the list of secondary partners.

---

## Screenshots (if applicable):

<img width="282" alt="2024-01-31 (1)" src="https://github.com/codeforpdx/codepdx_website/assets/83156697/bfb77f0f-935e-4673-ba10-5c369abd8143">
<img width="1048" alt="2024-01-31" src="https://github.com/codeforpdx/codepdx_website/assets/83156697/2fab0e55-7aa1-41ce-afb2-61f27fe56263">

---

## Future Steps/PRs Needed to Finish This Work (optional):

Determine whether their summary translates well enough from the original bulleted list to a single paragraph, or if more editing should be done.

This PR is currently slated to merge with main. Can be changed to merge with a new separate branch, if desired.

2024-02-02 02:35 UTC, Jared-Krajewski requested changes
I probably could have specified in the issue a bit beter. Looking to keep the bulleted format used in the issue and on their page https://urban.systems/About.

2024-02-06 02:35 UTC, andycwilliams commented
Getting bullet points and line breaks to render is proving unusually onerous. Do you have a preferred method?

2024-02-06 03:10 UTC, Jared-Krajewski commented
> Getting bullet points and line breaks to render is proving unusually onerous. Do you have a preferred method?

I would add the lines to be bulleted to a separate area in the object for urban systems.. something like 
```js
bulletedList: [
      'Scalable, Open, Distributed, Secure, Transaction Platform.',
      'Branded Community To Guarantee Interoperability Promise.',
      'Citizen Oriented Identity” To Facilitate Secure Data Transactions.'
    ]
 ```
 
 and then conditionally map it under the typography in the components as <ListItem />
 
 ```js
 {bulletedList &&
          bulletedList.length > 0 &&
          bulletedList.map((listItem, itemIndex) => (
            <ListItem sx={{ display: 'list-item' }} key={itemIndex} variant="body2">
              {listItem}
            </ListItem>
          ))}
```

you will get something like 

<img width="734" alt="Screenshot 2024-02-05 at 7 07 35 PM" src="https://github.com/codeforpdx/codepdx_website/assets/114430929/0841ec0a-a3ed-4b1a-bfc3-73e7116760fe">

since I just did it to make this example I just pushed the code as well. It has some errors in console and needs to be added to smallScreen and formatted for that as well.

2024-02-06 23:52 UTC, Jared-Krajewski approved these changes
🚀  If you want to fix that code of conduct link that would be cool too. If not it can be done separate. otherwise good to go.

2024-02-06 23:52 UTC, Jared-Krajewski commented on contributing.md
> +<!-- TODO: Will this contain its own Code of Conduct file? Or will it simply link to https://github.com/codeforpdx/codeofconduct? -->
this should link to GH code of conduct you referenced.

2024-02-06 23:52 UTC, Jared-Krajewski commented on contributing.md
> +- Join [CODE PDX Discord](https://discord.gg/uwqrPpyuap). If you run into any issues join the discord and drop a message in [introductions](https://discord.com/channels/1068260532806766733/1075286322
good catch on all the branding stuff.

2024-02-07 01:59 UTC, merged