143 enhancement update tao logo and link to their page
codeforpdx/codepdx_website pull request #144
Opened 2024-11-17 21:40 UTC by asaltveit

## This PR:

Resolves #143 

- Replaces the TAO logo with the new OIF logo
- Replaces "TAO" with "OIF"
- Links the logo to https://www.oregonif.org/
- Adds a grey rectangle background for the logo in dark mode

---

## Screenshots (if applicable):

Light mode
<img width="940" alt="Screenshot 2024-11-17 at 1 35 32 PM" src="https://github.com/user-attachments/assets/7aa854fe-5e57-4300-b630-fec69e7a8afa">

Dark mode
<img width="955" alt="Screenshot 2024-11-17 at 1 35 46 PM" src="https://github.com/user-attachments/assets/8f53b39c-7cd5-45fa-b909-36365cbeda0b">

---

## Future Steps/PRs Needed to Finish This Work (optional):

Add any other steps/PRs that may be needed to continue this work if this PR is just a step in the right direction.

2024-11-18 23:20 UTC, andycwilliams commented
Need more time to take a look. But real quick, "OIF Foundation" is redundant as it already stands for Oregon Innovation Foundation.

2024-11-19 00:26 UTC, Jared-Krajewski requested changes
Thanks for taking this on, I have a few comments for changes. If you would like the images I can send them on discord or push to the branch.

2024-11-19 00:26 UTC, Jared-Krajewski commented on src/components/home/partners/PrimaryPartner.jsx
> +        Empowering businesses and entrepreneurs, the OIF Foundation is creating and uniting a
This text was a direct copy from the TAO website. To maintain using a section from their website lets use.

`
The Oregon Innovation Foundation takes a comprehensive approach to cultivating civic innovation and empowering communities through technology to drive sustainable development.
`

Ill have to figure out something for the 4 sections under that text as those were also from their old website but that can be figured out later I guess.

2024-11-19 00:26 UTC, Jared-Krajewski commented on public/assets/partnerLogos/technology-association-of-oregon-logo-transparent-661x150.webp
The images are off center, the image from their website need the extra white space trimmed so they sit centered. I can't drop them here because of GH file restrictions on webp but can push the centered images, or send on discord if you'd like. 

original:
<img width="1152" alt="original" src="https://github.com/user-attachments/assets/72642522-e770-46a8-a440-a16d4288b333">
___
trimmed:
<img width="1134" alt="trimmed" src="https://github.com/user-attachments/assets/5f50b448-580d-4e6a-8e30-8d2b819fe014">

2024-11-19 00:26 UTC, Jared-Krajewski commented on public/assets/partnerLogos/background-grey-rectangle.webp
For dark mode, might be best to just use image with inverted text. 

<img width="964" alt="Screenshot 2024-11-18 at 4 22 46 PM" src="https://github.com/user-attachments/assets/ac08c335-bceb-466e-95d0-7ba7d4276ad0">

2024-11-20 20:58 UTC, asaltveit commented on public/assets/partnerLogos/technology-association-of-oregon-logo-transparent-661x150.webp
Yes, please push the centered images.

2024-11-20 22:22 UTC, asaltveit commented on public/assets/partnerLogos/technology-association-of-oregon-logo-transparent-661x150.webp
Actually, I went and did that.

2024-11-20 22:34 UTC, asaltveit commented
New look:

<img width="1008" alt="Screenshot 2024-11-20 at 2 29 44 PM" src="https://github.com/user-attachments/assets/cd294af5-ce9c-4d84-842a-c662980fe103">

<img width="1012" alt="Screenshot 2024-11-20 at 2 32 40 PM" src="https://github.com/user-attachments/assets/d0adcc09-e794-41a3-b575-1860a494ee23">

2024-11-23 03:01 UTC, Jared-Krajewski approved these changes
Awesome! Thanks for doing those the updates.

2024-11-24 04:01 UTC, merged