Fix footer formatting issue
codeforpdx/codepdx_website pull request #25
Opened 2023-10-21 21:18 UTC by Jared-Krajewski

## This PR:

Resolves #24

---

## Screenshots (if applicable):

![Screenshot 2023-10-21 at 2 17 01 PM](https://github.com/codeforpdx/codepdx_website/assets/114430929/bc8792a4-6f33-4abc-af13-04428cea510f)
 here.

---

## Future Steps/PRs Needed to Finish This Work (optional):

center socialLinks, fix roseLogo position, and clean up code.

2023-10-21 22:43 UTC, andycwilliams commented
A definite improvement. A minor thing is that it has a small unnecessary scroll bar.

<img width="1278" alt="Capture3" src="https://github.com/codeforpdx/codepdx_website/assets/83156697/67ba177a-ac6f-4abc-81f3-098d67b2d5ac">

---

Also, it's wonky with certain specific dimensions, apparently mainly with those that tablets use. This shows jumbled icons and text.

<img width="380" alt="Capture" src="https://github.com/codeforpdx/codepdx_website/assets/83156697/123cf50c-4320-454a-ac9a-d8a559df2dc6">

Changing `md` to `sm` on line 187 fixed this:

```
position: { xs: 'static', md: 'absolute' },
```

...although it also caused the text to overlap with the social media links. So it'll take more than that to resolve.

---

Whereas here it has the intended layout, just cut off. Worth noting that it also throws off the volunteer section, so that'll need addressing as well.

<img width="374" alt="Capture2" src="https://github.com/codeforpdx/codepdx_website/assets/83156697/dbc78776-6229-4ad5-8619-8586bdc095c0">

---

I haven't tested everything, so I'm not a huge help with solutions right now. For the moment I just wanted to point out what my browser is showing.

2023-10-21 22:49 UTC, Jared-Krajewski commented
This is up as a draft/WIP to link it to issue #24 Scott created. I believe all of the things you mentioned have been fixed. Just trying to figure out something pushing icons to the right in larger viewports then this is ready for review. I will change the status when its ready.

2023-10-21 23:07 UTC, andycwilliams commented
Cool cool. Just thought you wanted to work even more on the footer.

> I believe all of the things you mentioned have been fixed. Just trying to figure out something pushing icons to the right in larger viewports then this is ready for review.

Do you mean they're fixed in a branch you're working on but haven't yet pushed?

Anyway, in terms of addressing issue 24 this is good.

2023-10-21 23:46 UTC, Jared-Krajewski commented
> Cool cool. Just thought you wanted to work even more on the footer.
> 
> > I believe all of the things you mentioned have been fixed. Just trying to figure out something pushing icons to the right in larger viewports then this is ready for review.
> 
> Do you mean they're fixed in a branch you're working on but haven't yet pushed?
> 
> Anyway, in terms of addressing issue 24 this is good.

Yes they are in an un-published branch.

2023-10-22 00:35 UTC, Jared-Krajewski commented
The text still goes a little crazy near mobile view and will need to be fixed in the future. Other issues should be addressed besides styling that will be changed after figma edits.

https://github.com/codeforpdx/codepdx_website/assets/114430929/b055617c-ae77-4a9c-b18d-da5d7a525309

2023-10-22 15:40 UTC, ogorman89 commented
Much better. 

A couple of questions:

Do we want the footer to stick to the bottom of the screen? Right now, it floats up to the content. 

![Screen Shot 2023-10-22 at 8 29 59 AM](https://github.com/codeforpdx/codepdx_website/assets/3335277/1a195398-6f82-416c-b61a-67cf3c69eb22)

Visually, should we hide the CODE PDX in the mobile view? We still have "2023 CODE PDX" at the very bottom. I think a centered logo might look more symmetrical. 

![Screen Shot 2023-10-22 at 8 36 47 AM](https://github.com/codeforpdx/codepdx_website/assets/3335277/4fbb6217-d80d-42a2-badf-b8dc1bf57a3b)

Links in the tablet section do appear to get jumbled, as Andy noted. Should we switch to the compact mobile view for tablet viewing? Things get a bit crowded and the mobile stack looks so clean 😎 There is also the issue of the logo color being too similar to the background. 

![Screen Shot 2023-10-22 at 8 35 42 AM](https://github.com/codeforpdx/codepdx_website/assets/3335277/a15ea7bd-49f5-489b-9320-bfa45a2bf276)

I'm in favor of merging as is since the major bug is fixed.

2023-10-22 15:42 UTC, ogorman89 approved these changes
Resolves #24: see comments on potential enhancements.

2023-10-22 17:15 UTC, Jared-Krajewski commented
@ogorman89 

 I think with it floating up to the contents there should be no issue since the page will be long enough to keep it at the bottom of the view but I could be wrong. 

Ill check with Hugh/Flo and a few others if they have a preference for removing the text next to the logo in mobile view. I was thinking about actually keeping the legal links to the right and the rose to the left but under the socialLinks if that makes sense. I think I might build out a few of the select components that drastically change in mobile view on Figma so we can have more of a plan on mobile view.  I will try to get that done sooner than later.

I think its mentioned earlier in this PR but the colors aren't final. I need to put the theme into Figma and then implement that to our theme.js after its reviewed. The links will scramble at certain resolutions when you do responsive but if you set it to any of the smaller devices specifically I think there are no issues, If its causing issues we can change the breakpoint to a larger view like you suggested.

2023-10-22 21:38 UTC, andycwilliams approved these changes
I'm not seeing the text overlap with the links anymore, so that looks all fixed.

The text does still get jumbled in certain dimensions. However, it only seems to happen within a pretty small window (i.e. 602 width to about 745 width). I honestly don't know how many devices actually fall within that range. It doesn't get jumbled in any of the predefined dimensions when using devtools, including the tablet ones.

In mobile views, `CODE PDX` may look nicer when placed under the logo than side-by-side as Ian suggested. Symmetrical tends to be more pleasing, although it doesn't look bad as-is so it's not a real issue for me.

I also would rather the footer stick to the bottom on all viewports. But I agree we can wait until there's more content on each page, then see.

That said, I'll approve this now. It resolves the issue and any changes can wait for a future PR.

2023-10-22 22:21 UTC, xscottxbrownx commented
> @ogorman89
> 
> We probably do want it down. I think with it floating up to the contents there should be no issue since the page will be long enough to keep it at the bottom of the view but I could be wrong and will see if I can figure out a fix.
> 
> Ill check with Hugh/Flo and a few others if they have a preference for removing the text next to the logo in mobile view. I was thinking about actually keeping the legal links to the right and the rose to the left but under the socialLinks if that makes sense. I think I might build out a few of the select components that drastically change in mobile view on Figma so we can have more of a plan on mobile view. I will try to get that done sooner than later.
> 
> I think its mentioned earlier in this PR but the colors aren't final. I need to put the theme into Figma and then implement that to our theme.js after its reviewed. The links will scramble at certain resolutions when you do responsive but if you set it to any of the smaller devices specifically I think there are no issues, If its causing issues we can change the breakpoint to a larger view like you suggested.

I had to do this with another project of mine, where I dynamically added `position: fixed` or not on the footer. I can try to find it in the code if needed.    Because when content is too short for screen, we want it fixed to bottom.  But when content is longer than screen, we do not.    Don't really want a frame of navbar and footer, with scrollable content in-between.

2023-10-22 22:36 UTC, Jared-Krajewski commented
@andycwilliams  > In mobile views, `CODE PDX` may look nicer when placed under the logo than side-by-side as Ian suggested. Symmetrical tends to be more pleasing, although it doesn't look bad as-is so it's not a real issue for me.

It was like that and there was a comment asking it to be side by side so it was changed. Mobile Figma board will be made and design input will be done in a group session or through Figma feedback. 

@xscottxbrownx I have it written up on local but if you find it please send it over so I can compare how I did it (not sure my solution is the best), its messing up a blob but otherwise works, when I get that fixed I will push it before I merge this.

2023-10-22 22:51 UTC, xscottxbrownx requested changes
There is an issue on skinnier mobile devices (like galaxy fold) where the spacing between the social media icons is too large and messes up everything.   I made two comments that fix this.

I don't see any other issues.  No jumbled text/link/alignment, no scrollbars, etc.

2023-10-22 22:51 UTC, xscottxbrownx commented on src/components/global/Footer.jsx
>        padding: '25px',
make this `padding` in `renderSocialLinks` only a `py: '25xp'`, then see comment on line 189.

2023-10-22 22:51 UTC, xscottxbrownx commented on src/components/global/Footer.jsx
> +      <Box display={'flex'}>{renderSocialLinks}</Box>
Make this instead a `<Stack direction="row" spacing={{xs: 2, sm: 3}}>{renderSocialLinks}</Stack>`.     You could play with the spacing on `sm` if you want it bigger, but I didn't test any bigger than this.   `Stack` is flex by default.

2023-10-23 16:09 UTC, xscottxbrownx commented
And merge into Dev instead yeah?

2023-10-23 16:46 UTC, Jared-Krajewski commented
> And merge into Dev instead yeah?

I had it set to main so when anyone creates a branch they don't have that footer bug and we had no other changes in Dev (currently still don't) that would require a second pull request with the exact same content into main if i do that. so this just skips a PR with no other changes, but generally yes Dev instead. I guess for the sake of consistency I can change it.

2023-10-23 19:27 UTC, xscottxbrownx approved these changes

2023-10-23 19:27 UTC, merged