Issue 66/secondary partner styling enhancements
codeforpdx/codepdx_website pull request #78
Opened 2023-12-19 03:01 UTC by andycwilliams

## This PR:

Resolves #66

A relatively quick go at it. Very possibly some minor adjustments left to make but it should hopefully address all of the issue's core needs.

---

## Screenshots (if applicable):

<img width="1018" alt="2023-12-18 (4)" src="https://github.com/codeforpdx/codepdx_website/assets/83156697/6fb2c804-a70b-4870-9713-b7df8f54573f">

---

## Future Steps/PRs Needed to Finish This Work (optional):

Fine-tune layout as needed.

2023-12-19 17:23 UTC, xscottxbrownx requested changes

2023-12-19 17:23 UTC, xscottxbrownx commented on src/components/global/Footer.jsx
> +          aria-label="CODE PDX"
not sure it needs an aria-label if it has an alt, but glad to change this for continuityl

2023-12-19 17:23 UTC, xscottxbrownx commented on src/components/home/partners/SecondaryPartners.jsx
> +            p={'40px 15% 5% 0'}
Any reason this wouldn't have the same padding as `testimonial`? the text doesn't line up for testimonial one and two due to this.

2023-12-19 17:23 UTC, xscottxbrownx commented on src/components/home/partners/SecondaryPartners.jsx
> +            variant="body1"
not necessary. the `Typography` MUI component does not have a `display` attribute. This does nothing.

2023-12-19 17:23 UTC, xscottxbrownx commented on src/components/home/partners/SecondaryPartners.jsx
> +            p={'0 5% 10% 5%'}
any reason for this padding not to be the same as `testimonial Author`?

2023-12-19 17:23 UTC, xscottxbrownx commented on src/components/home/partners/SecondaryPartners.jsx
> +    // This Container element causes the second partners to be narrower than the primary partner, even on small screens.
I would personally prefer them to be the same size horizontally. They are already a different layout and have less info than the primary partner. I think that's enough to delineate the two.

2023-12-19 17:23 UTC, xscottxbrownx commented on src/components/home/partners/SecondaryPartners.jsx
> +// Data Imports
here you used "Data Imports", in `VolunteerSteps` you used "Component Imports", in `ProjectsBrief` it's "Data Imports"...

so maybe change it in `VolunteerSteps` to match?  It honestly doesn't matter, but if we're going through and changing for consistency, then that one too.

2023-12-19 17:23 UTC, xscottxbrownx commented on src/components/home/partners/SecondaryPartners.jsx
>    testimonial: PropTypes.string.isRequired,
If we are moving these around, I'd prefer 
```
testimonial
testimonialAuthor
testimonialTwo
testimonialAuthorTwo
```
but would actually prefer `testimonialAuthorTwo` to be changed in the codebase to `testimonialTwoAuthor` 😂

2023-12-19 17:23 UTC, xscottxbrownx commented on src/components/home/partners/SecondaryPartners.jsx
> +        // Below not necessary?
Nope not necessary.  Default for `display: flex` is row already...

MUI `<Grid>` is based on flexbox

<img width="508" alt="Screenshot 2023-12-19 at 8 59 50 AM" src="https://github.com/codeforpdx/codepdx_website/assets/71395931/bfec99bb-2c6d-4fb3-a3b7-a2c110e18577">

2023-12-19 17:23 UTC, xscottxbrownx commented on src/components/home/partners/SecondaryPartners.jsx
>          {testimonialTwo ? (
on both `LargeScreenComponent` and `SmallScreenComponent` there are ternaries used that are just something to the effect of:

```js
{condition ? (
    <Returned JSX>
) : null}
```

if it's "this" or "null", I think it's more commonplace in React (and I'd personally prefer) to use the JS AND operand short-circuiting instead:

```js
{condition && (
    <Returned JSX>
)}
```

if condition is true, the right of AND gets evaluated and rendered.

2023-12-19 17:23 UTC, xscottxbrownx commented on src/components/home/partners/SecondaryPartners.jsx
> +            variant="body1"
not necessary. the `Typography` MUI component does not have a `display` attribute. This does nothing.

2023-12-19 17:23 UTC, xscottxbrownx commented on src/components/home/partners/SecondaryPartners.jsx
>              alt={`${company} logo`}
This `<Box>` could be self-closing instead.

2023-12-19 17:23 UTC, xscottxbrownx commented on src/components/home/partners/SecondaryPartners.jsx
> +      <Grid item pl={'6%'} pr={'1%'} {...partnerGridStyle} order={contentOrder}>
### This whole section on, I'm not sure about this current approach...

There's just so much inconsistency with all the different paddings on different things. It's causing so the text isn't lined up with the logos vertically (when in desktop), the authors have different paddings, etc.

Like visually (besides the vertical alignment) looks like it does the job, but under the hood as a dev - it seems like plug in whatever wherever to get there.

---

I feel like the left `Grid item` (company logo on first `secondaryPartner`) should be vertically and horizontally centered.

Then the right `Grid item` should be the same, but that encompasses all the testimonials and authors it has. This `Grid item` or the `Grid container` itself should have the padding/margin applied for the styling properly.

Then within the right `Grid item` make the spacing between elements as see fit, but should just be `py` or `pt` and `pb` at that point.  Or even better use a `Stack` and `spacing={whatever}` so it's all consistent and easy to determine what the expected behavior/outcome is. Future maintainability.

2023-12-19 21:19 UTC, andycwilliams commented on src/components/global/Footer.jsx
> +          aria-label="CODE PDX"
Missed that. I was searching through the code and just updating the name wherever it appeared.

2023-12-19 21:23 UTC, andycwilliams commented on src/components/home/partners/SecondaryPartners.jsx
> +            p={'40px 15% 5% 0'}
Fixed

2023-12-19 21:27 UTC, andycwilliams commented on src/components/home/partners/SecondaryPartners.jsx
> +            p={'0 5% 10% 5%'}
For some reason it looks less consistent, at least to me. But I can change it.

2023-12-19 21:27 UTC, andycwilliams commented on src/components/home/partners/SecondaryPartners.jsx
> +    // This Container element causes the second partners to be narrower than the primary partner, even on small screens.
That's my thinking too.

2023-12-20 01:08 UTC, xscottxbrownx reviewed
see the photos for what I was trying to explain with padding earlier

2023-12-20 01:08 UTC, xscottxbrownx commented on src/components/home/partners/SecondaryPartners.jsx
> +            variant="caption"
Think the padding for `testimonialAuthorTwo` should be `0 5% 8% 5%` to match `testimonialAuthor`

Believe line 146 is reason why the is more space between the second testimonial and it's author vs the first.
<img width="148" alt="Screenshot 2023-12-19 at 4 57 17 PM" src="https://github.com/codeforpdx/codepdx_website/assets/71395931/5a230807-3e7a-43c9-9501-cd25094b92c6">
<img width="531" alt="Screenshot 2023-12-19 at 4 57 43 PM" src="https://github.com/codeforpdx/codepdx_website/assets/71395931/0e135445-b00b-45bc-84a8-045d94f69c04">

2023-12-20 01:09 UTC, xscottxbrownx commented on src/components/home/partners/SecondaryPartners.jsx
> +            p={'0 5% 10% 5%'}
see photos below

2023-12-25 02:13 UTC, Jared-Krajewski requested changes
padding seems to still be at previous values once viewports get smaller. otherwise good enough for me once this & Scott's requests are fulfilled.

https://github.com/codeforpdx/codepdx_website/assets/114430929/60226884-9bec-4a31-94dc-f568ee04343c

2023-12-25 07:08 UTC, andycwilliams commented
It should be more consistent along viewports, though the code itself is kind of janky (padding measured by pixels as well as percentages). More so than I'd like but this is what I have time for at the moment.

Let me know if this is good enough. I'll have more time to tweak it later on.

2023-12-27 21:55 UTC, Jared-Krajewski commented
> It should be more consistent along viewports, though the code itself is kind of janky (padding measured by pixels as well as percentages). More so than I'd like but this is what I have time for at the moment.
> 
> Let me know if this is good enough. I'll have more time to tweak it later on.
![Screenshot 2023-12-27 at 1 47 03 PM](https://github.com/codeforpdx/codepdx_website/assets/114430929/630627e5-1ec1-45b3-94da-eb2deb299bbf)


https://github.com/codeforpdx/codepdx_website/assets/114430929/043cacd7-aa99-4597-98fb-c16e43613c32



the card heights and width are all quite different now and weren't supposed to be changed as part of this. Those need to be reverted to previous values, the goal was to trim some of the height from the ORDSN card by widening its the text areas within the current box, remove some of the extra padding from authors and match the rest of the cards to whatever height that ended up being. Let me know if you have time to fix this if not I can try to finish it when I have time.

2023-12-28 04:28 UTC, andycwilliams commented
Still not finished. Need to center the author text, doesn't look great on smaller viewports, etc. But I don't have too much more time for this one, since I still have a couple other issues to do. @Jared-Krajewski can take over if you want.

I took a swing at refactoring it so that there wouldn't need to be quite so much padding in so many areas. Can change it back if you don't like. I added `Box`es to the grid items and imo it's better but still needs fine-tuning.

There are some annoying things, like the `Container` on line 155 makes it more consistent with `PrimaryPartner` on larger screens but less so on smaller ones. 

The `LargeScreenComponent` and `SmallScreenComponent` make it slightly more awkward to deal with, since this is one of the only places we use media queries. Otherwise we use the breakpoints that Material UI comes with. But I didn't want to just refactor the entire thing.

2023-12-28 07:17 UTC, xscottxbrownx commented
pushed fix for centering testimonial authors... switched `caption` variant to `subtitle2` for quick fix.   Other option would've been to adjust the theme of the `caption` variant as that was the issue.

2023-12-30 18:50 UTC, xscottxbrownx commented
> The `LargeScreenComponent` and `SmallScreenComponent` make it slightly more awkward to deal with, since this is one of the only places we use media queries. Otherwise we use the breakpoints that Material UI comes with. But I didn't want to just refactor the entire thing.

If you don't like the two separate components, I refactored into just a single component with the styling conditionals built in. Not sure if it's cleaner/better, but maybe 🤷🏻‍♂️

```js
// Material UI Imports
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';
import useMediaQuery from '@mui/material/useMediaQuery';
import { useTheme } from '@mui/material/styles';
// Other Library Imports
import { PropTypes } from 'prop-types';
// Component Imports
import { secondaryPartnerList } from './secondaryPartnerList';


const partnerGridStyle = {
  xs: 12,
  md: 6,
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  flexDirection: 'column',
  p: '4%'
};

const calculateGradientStyle = (isSmallScreen, index) => {
  if (isSmallScreen) {
    return 'linear-gradient(180deg, rgba(217, 217, 217, 0) 38.54%, rgba(217, 217, 217, 0.4) 82.29%)';
  }

  return index % 2 === 0
    ? 'linear-gradient(90deg, rgba(217, 217, 217, 0) 38.54%, rgba(217, 217, 217, 0.4) 82.29%)'
    : 'linear-gradient(270deg, rgba(217, 217, 217, 0) 38.54%, rgba(217, 217, 217, 0.4) 82.29%)';
};

const SecondaryPartners2 = () => {
  const theme = useTheme();
  const isSmallScreen = useMediaQuery(theme.breakpoints.down('md'));

  return (
    <Container>

      {secondaryPartnerList.map((partner, index) => {
        const gradientStyle = calculateGradientStyle(isSmallScreen, index);
        return (
          <Grid
            key={partner.company}
            container
            sx={{
              background: gradientStyle,
              borderRadius: '30px',
              minHeight: isSmallScreen ? 'auto' : '350px',
              marginBottom: isSmallScreen ? '15%' : '100px'
            }}
          >
            <Grid item {...partnerGridStyle} order={isSmallScreen ? 0 : index % 2}>
              <a href={partner.website} target="_blank" rel="noopener noreferrer">
                <Box
                  component="img"
                  alt={`${partner.company} logo`}
                  aria-label={`${partner.company} logo`}
                  src={partner.partnerLogo}
                  width={isSmallScreen ? '100px' : '250px'}
                />
              </a>
            </Grid>
            <Grid item {...partnerGridStyle} order={isSmallScreen ? 1 : (index + 1) % 2}>
              <Stack spacing={1}>
                <Typography variant="body1">{partner.testimonial}</Typography>
                <Typography
                  variant="subtitle2"
                  sx={{
                    fontWeight: 'bold',
                    textAlign: 'center'
                  }}
                >
                  {partner.testimonialAuthor}
                </Typography>
              </Stack>
              <br />
              <Stack spacing={1}>
                {partner.testimonialTwo && (
                  <Typography variant="body1">{partner.testimonialTwo}</Typography>
                )}
                {partner.testimonialTwoAuthor && (
                  <Typography variant="subtitle2" sx={{ fontWeight: 'bold', textAlign: 'center' }}>
                    {partner.testimonialTwoAuthor}
                  </Typography>
                )}
              </Stack>
            </Grid>
          </Grid>
        );
      })}

    </Container>
  );
};

SecondaryPartners2.propTypes = {
  index: PropTypes.number.isRequired,
  company: PropTypes.string.isRequired,
  testimonial: PropTypes.string.isRequired,
  testimonialAuthor: PropTypes.string,
  testimonialTwo: PropTypes.string,
  testimonialTwoAuthor: PropTypes.string,
  partnerLogo: PropTypes.string.isRequired,
  website: PropTypes.string.isRequired
};

export default SecondaryPartners2;
```

`partner` in the .map() could be destructured if wanted.

2024-01-09 20:02 UTC, andycwilliams commented
Is there anything else needed from this?

2024-01-23 03:29 UTC, Jared-Krajewski approved these changes
Good enough for now. we can touch back on this another time if we want to update anything.

2024-01-23 04:45 UTC, xscottxbrownx approved these changes

2024-01-23 05:51 UTC, merged