Issue 73/add ceti to partners
codeforpdx/codepdx_website pull request #86
Opened 2023-12-31 04:15 UTC by andycwilliams

## This PR:

Resolves #73 

Adds CETI to the list of secondary partners. Looks out of whack because #78 isn't merged yet. Once that's done this will look better. Additionally added a testimonial/summary for Epicodus.

Also, I tried organizing the image assets a bit more. The only difference should be that they're in subfolders now. Yet they render differently on the Projects page. Although in the Projects Brief section they seem unchanged. 

That was outside of the scope for this PR, so I put all that into separate commits and they should be easily undone. Hence leaving this as a draft for now.

---

## Screenshots (if applicable):

<img width="1261" alt="2023-12-30 (7)" src="https://github.com/codeforpdx/codepdx_website/assets/83156697/d53aaa58-834f-4431-87b4-6c8f4a44a546">

---

## Future Steps/PRs Needed to Finish This Work (optional):

Merge the secondary partner styling updates.

Decide whether it's worth dividing the images into subfolders.

2024-01-02 00:11 UTC, xscottxbrownx requested changes

2024-01-02 00:11 UTC, xscottxbrownx commented on src/components/home/partners/secondaryPartnerList.js
> +      "Epicodus's mission is to help people learn the skills they need to get great jobs. For us, “great jobs” means jobs in growing industries that pay well and provide rewarding work. Beyond the pa
kill the extra period at end of paragraph

2024-01-02 00:11 UTC, xscottxbrownx commented on src/components/home/partners/secondaryPartnerList.js
> +      'A Creative and Emergent Technology Institute, CETI champions lifelong learning and collaborative, interdisciplinary innovation in creative and emergent technologies',
I'd prefer either the **Mission** section of their `About` page:
```
CETI champions lifelong learning and collaborative, interdisciplinary innovation in creative and emergent technologies. Through radically inclusive community participation, we rapidly build expertise for an astonishing diverse group of people. CETI contends that our most urgent challenges can be imaginatively addressed through art, storytelling and invention.
```

OR

the **Who We Are** section of their `About` page:
```
CETI prioritizes including and collaborating with communities previously marginalized, under-represented, and under-served  in tech. Through our lived experiences and diversity in demographics, we bring a diversity of critical and cultural lenses to the intentional design of our programs, as well as a laser-focus on inclusion and support of communities significantly under-represented in technology conversations.  

CETI is a collective—of artists, technologists, storytellers, educators, researchers, innovators, and leaders—composed of experts and lifelong learners, excited to share our ideas and skills. A subset of us engage with each project, alternatively taking on roles as learners, facilitators, creators, producers, and advisors, wielding the powerful tools of art, emerging technology, and storytelling  to imagine and create inclusive, just futures.
```

2024-01-02 01:25 UTC, andycwilliams commented on src/components/home/partners/secondaryPartnerList.js
> +      'A Creative and Emergent Technology Institute, CETI champions lifelong learning and collaborative, interdisciplinary innovation in creative and emergent technologies',
The first one is more concise and to-the-point imo. I vote that one.

2024-01-03 21:17 UTC, ogorman89 approved these changes
Looks good. I think once we get this and #78 merged we should give it one more look for adjustments.

2024-01-04 01:10 UTC, Jared-Krajewski requested changes
The folder changes aren't really part of this issue so not sure how that fell into this PR. If we are going to separate then it should be a bit more specific instead of `codepdxImages`. maybe `logos` for the logos. Also if we are putting them all into folders, we should put them all into folders not just some of them.

The changes regarding issue #73 are fine to me otherwise.

2024-01-04 05:22 UTC, Jared-Krajewski approved these changes

2024-01-04 19:16 UTC, andycwilliams commented
@xscottxbrownx Once you approve we can get this merged

2024-01-04 21:04 UTC, xscottxbrownx approved these changes

2024-01-04 22:54 UTC, merged